"""checkins table

Revision ID: 35aab96ba8d2
Revises: ecc6a2c90c95
Create Date: 2018-08-10 23:23:50.423641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35aab96ba8d2'
down_revision = 'ecc6a2c90c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=True),
    sa.Column('checkin_note', sa.String(length=255), nullable=True),
    sa.Column('checkins_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkins_list'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employes_first_name'), 'employes', ['first_name'], unique=False)
    op.create_index(op.f('ix_employes_last_name'), 'employes', ['last_name'], unique=False)
    op.create_index(op.f('ix_employes_middle_name'), 'employes', ['middle_name'], unique=False)
    op.create_index(op.f('ix_holiday_holiday_date'), 'holiday', ['holiday_date'], unique=True)
    op.create_index(op.f('ix_lists_sick_list_number'), 'lists', ['sick_list_number'], unique=True)
    op.create_index(op.f('ix_patients_first_name'), 'patients', ['first_name'], unique=False)
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_middle_name'), 'patients', ['middle_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_middle_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name'), table_name='patients')
    op.drop_index(op.f('ix_lists_sick_list_number'), table_name='lists')
    op.drop_index(op.f('ix_holiday_holiday_date'), table_name='holiday')
    op.drop_index(op.f('ix_employes_middle_name'), table_name='employes')
    op.drop_index(op.f('ix_employes_last_name'), table_name='employes')
    op.drop_index(op.f('ix_employes_first_name'), table_name='employes')
    op.drop_table('checkins')
    # ### end Alembic commands ###
