"""status_note

Revision ID: 4f5e898e8c08
Revises: dce7853eda88
Create Date: 2018-09-17 22:24:11.398668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5e898e8c08'
down_revision = 'dce7853eda88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('doctor_who_open_list', sa.Integer(), nullable=True))
    op.add_column('lists', sa.Column('status_note', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'lists', 'employes', ['doctor_who_open_list'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'status_note')
    op.drop_column('lists', 'doctor_who_open_list')
    # ### end Alembic commands ###
