"""add checkins

Revision ID: dce7853eda88
Revises: a864508dd9dd
Create Date: 2018-09-07 09:41:55.746598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce7853eda88'
down_revision = 'a864508dd9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    op.add_column('lists', sa.Column('first_checkin_fact', sa.Date(), nullable=True))
    op.add_column('lists', sa.Column('first_checkin_note', sa.String(length=255), nullable=True))
    op.add_column('lists', sa.Column('second_checkin_fact', sa.Date(), nullable=True))
    op.add_column('lists', sa.Column('second_checkin_note', sa.String(length=255), nullable=True))
    op.add_column('lists', sa.Column('vkk_fact', sa.Date(), nullable=True))
    op.add_column('lists', sa.Column('vkk_note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'vkk_note')
    op.drop_column('lists', 'vkk_fact')
    op.drop_column('lists', 'second_checkin_note')
    op.drop_column('lists', 'second_checkin_fact')
    op.drop_column('lists', 'first_checkin_note')
    op.drop_column('lists', 'first_checkin_fact')
    op.create_table('checkins',
    sa.Column('checkin_id', sa.INTEGER(), nullable=False),
    sa.Column('checkin_date', sa.DATE(), nullable=True),
    sa.Column('checkin_note', sa.VARCHAR(length=255), nullable=True),
    sa.Column('co_type', sa.INTEGER(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    # ### end Alembic commands ###
