"""dia link

Revision ID: fa9e5f32c8dc
Revises: 13578a91223f
Create Date: 2018-09-25 00:17:53.057072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9e5f32c8dc'
down_revision = '13578a91223f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lists', 'diacrisis', ['diagnoses_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    # ### end Alembic commands ###
